name: Sync to Personal Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Remove workflow files and push to personal repo
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        # Remove the .github directory
        rm -rf .github
        
        # Configure git
        git config user.name "Nunomatos7"
        git config user.email "nuno@example.com"
        
        # Unset any existing credential helpers
        git config --unset-all credential.helper || true
        
        # Stage changes
        git add -A
        git commit -m "Sync from organization repo" || echo "No changes to commit"
        
        # Push directly with token in URL
        git push https://Nunomatos7:${PERSONAL_TOKEN}@github.com/Nunomatos7/memorus.git HEAD:main --force