name: Sync to Personal Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_TOKEN }}
        
    - name: Copy files from memor-us-app to root and push to personal repo
      run: |
        # Remove the .github directory
        rm -rf .github
        
        # Enable dotglob to include hidden files
        shopt -s dotglob
        
        # Move everything from memor-us-app to root level more carefully
        if [ -d "memor-us-app" ]; then
          # List what we're about to move (for debugging)
          echo "Contents of memor-us-app:"
          ls -la memor-us-app/
          
          # Move all files and directories
          mv memor-us-app/* . 2>/dev/null || true
          mv memor-us-app/.[^.]* . 2>/dev/null || true
          
          # Remove the now-empty directory
          rmdir memor-us-app 2>/dev/null || true
        fi
        
        # List final structure (for debugging)
        echo "Final structure:"
        ls -la
        
        # Configure git
        git config user.name "Nunomatos7"
        git config user.email "nuno.esteves@ua.pt"
        
        # Stage changes
        git add -A
        git commit -m "Sync from organization repo (moved to root)" || echo "No changes to commit"
        
        # Add remote and push
        git remote add personal https://github.com/Nunomatos7/memorus.git
        git push personal HEAD:main --force