name: Sync to Personal Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Remove workflow files and push to personal repo
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        # Remove the .github directory
        rm -rf .github
        
        # Configure git
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # Add remote and push (force push to overwrite)
        git remote add personal https://${PERSONAL_TOKEN}@github.com/Nunomatos7/memorus.git
        git add -A
        git commit -m "Sync from organization repo" || echo "No changes to commit"
        git push personal HEAD:main --force