name: Sync to Personal Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Remove workflow files and push to personal repo
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        # Remove the .github directory
        rm -rf .github
        
        # Configure git with your username and token
        git config user.name "Nunomatos7"
        git config user.email "your-email@example.com"
        
        # Configure git to use the token for authentication
        git config url."https://${PERSONAL_TOKEN}@github.com/".insteadOf "https://github.com/"
        
        # Stage changes
        git add -A
        git commit -m "Sync from organization repo" || echo "No changes to commit"
        
        # Add remote and push
        git remote add personal https://github.com/Nunomatos7/memorus.git
        git push personal HEAD:main --force