name: Sync to Personal Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Remove workflow files and push to personal repo
      run: |
        # Remove the .github directory
        rm -rf .github
        
        # Configure git
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        
        # Stage the removal of .github directory
        git add -A
        git commit -m "Sync from organization repo (excluding workflows)" || echo "No changes to commit"
        
        # Push to personal repo
        git remote add personal https://${{ secrets.PERSONAL_TOKEN }}@github.com/Nunomatos7/memorus.git
        git push personal HEAD:main --force